ENV: dev
API:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/new-api"
  ImageTag: "dev-baeb537"
  API_KEY: "testets"
UI:
  Image: "habor.analytichpxv3.online/kubernetes-workshop/new-ui"
  ImageTag: "0.0.1"
